version: "3.8"

services:
  apache:
    build:
      context: apache
    hostname: lr-apache
    container_name: cont-lr-apache
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - ./apache/vhosts:/etc/apache2/sites-available
      - ./apache/www:/var/www

networks:
  default:
    # this network is related to a main container with mariadb and all my databases
    # in this way I avoid creating a db container for each project check this file for more info:
    # prj_docker_imgs/mariadb-univ/docker-compose.yml
    name: mariadb-univ_net
    external: true