version: "3.8"

services:
  apache:
    build: ./apache
    container_name: cont-lr-apache
    hostname: lr-apache

    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - ./apache/vhosts:/etc/apache2/sites-available
      - ./apache/www:/var/www

  mariadb:
    build: ./mariadb
    container_name: cont-lr-mariadb
    hostname: lr-mariadb

    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root

    volumes:
      # .env.DB_FOLDER=/Users/ioedu/projects/db_mariadb
      - ./mariadb/initdb:/docker-entrypoint-initdb.d/
      - ./mariadb/mysql:/var/lib/mysql

    ports:
      - "3308:3306"
networks:
  default:
    # this network is related to a main container with mariadb and all my databases
    # in this way I avoid creating a db container for each project check this file for more info:
    # prj_docker_imgs/mariadb-univ/docker-compose.yml
    name: mariadb-univ_net
    external: true